### PR TITLE
Add linting

### PR DESCRIPTION
**Pull request by kandros**
add linting with tslint

> for [open source saturday - milan 22/04/2017](https://www.meetup.com/it-IT/Open-Source-Saturday-Milano/events/238904689/)

### CODE REVIEW

**Comment by schickling** [comment]
Can you `lint` automatically when running `build`?

**Comment by kandros** [comment]
done, test coming soon

**Comment by schickling** [comment]
Awesome! Do you mind setting up circle CI for this as well?

**Comment by kandros** [comment]
can you add build trigger on pull request commits?

**Pull request merged**
